rapids-wheels-anaconda-github: use a stable directory for uploads (#264)
#263 broke the path in `wheels-publish` workflows where we upload to PyPI.

The relevant code there expects packages to be in `dist/` ([rapidsai/shared-workflows - .github/workflows/wheels-publish.yaml](https://github.com/rapidsai/shared-workflows/blob/3f5f9d01f3873916bf830fdc3e0fd684ccc0befb/.github/workflows/wheels-publish.yaml#L149)), but in #263 I replaced that with `mktemp`.

```text
ERROR    InvalidDistribution: Cannot find file (or expand pattern): 'dist/*'    
Error: Process completed with exit code 1.
```

([jupyterlab-nvdashboard build link](https://github.com/rapidsai/jupyterlab-nvdashboard/actions/runs/28184382922/job/83483178079))

This proposes making that location configurable, so that related steps can all share the same value.

## Notes for Reviewers

Deployment order:

1. merge this PR
2. wait for new images to be built: https://github.com/rapidsai/ci-imgs/actions/workflows/push.yaml
3. merge `shared-workflows` PR: https://github.com/rapidsai/shared-workflows/pull/583

Authors:
  - James Lamb (https://github.com/jameslamb)

Approvers:
  - Gil Forsyth (https://github.com/gforsyth)

URL: https://github.com/rapidsai/gha-tools/pull/264